import { BasicColumn } from '/@/components/Table';
import { FormSchema } from '/@/components/Table';
import { ref, h } from 'vue';
import { Image } from 'ant-design-vue';
const baseUrl = import.meta.env.VITE_GLOB_API_URL;
const v = {
  tag: 'h1',
};

export const columns: BasicColumn[] = [
  {
    title: '设备编号',
    dataIndex: 'equipment_number',
    width: 120,
    align: 'left',
  },
  {
    title: '设备名称',
    dataIndex: 'name',
    width: 100,
  },
  //  {
  //    title: '设备分组',
  //    dataIndex: 'group',
  //    width: 100,
  //  },
  //  {
  //    title: '运营状态',
  //    dataIndex: 'status',
  //    width: 100,
  //  },
  {
    title: '点位编号',
    dataIndex: 'point_id',
    width: 100,
  },
  {
    title: '点位名称',
    dataIndex: 'point_name',
    width: 100,
  },
  {
    title: '设备状态',
    dataIndex: 'status',
    width: 100,
  },
  // {
  //   title: '设备RTSP地址',
  //   dataIndex: 'order',
  //   width: 100,

  // },
  // {
  //   title: '拍照间隔时间',
  //   dataIndex: 'interval_time',
  //   width: 100,
  // },
  // {
  //   title: '是否大屏显示',
  //   dataIndex: 'is_screenShow',
  //   width: 100,
  //   customRender: ({ record }) => {
  //     const is_screenShow = record.is_screenShow;
  //     const text = is_screenShow ? '是' : '否';
  //     return h(() => text);
  //   },
  // },
  {
    title: '添加日期',
    dataIndex: 'create_datetime',
    width: 180,
  },
  //  {
  //    title: '科',
  //    dataIndex: 'family',
  //    width: 100,
  //  },
  //  {
  //    title: '创建时间',
  //    dataIndex: 'create_datetime',
  //    width: 180,
  //  },
  //  {
  //   title: '图像',
  //   dataIndex: 'url',
  //   width: 80,
  //   customRender: ({ record }) => {
  //     const url = record.url;
  //     // console.log(baseUrl + url)
  //     return h(Image, { src:  'http://localhost:8000' + url, width: 40 });
  //   },
  // },
];

export const searchFormSchema: FormSchema[] = [
  // {
  //   field: 'equipment_number',
  //   label: '设备编号',
  //   component: 'Input',
  //   colProps: { span: 6 },
  // },
  {
    field: 'name',
    label: '设备名称',
    component: 'Input',
    colProps: { span: 6 },
  },
  // {
  //   field: 'group',
  //   label: '设备分组',
  //   component: 'Input',
  //   colProps: { span: 6 },
  // },
  // {
  //   field: 'group',
  //   label: '运营状态',
  //   component: 'Input',
  //   colProps: { span: 6 },
  // },
  {
    field: 'status',
    label: '设备状态',
    component: 'Input',
    colProps: { span: 6 },
  },
  // {
  //   field: 'group',
  //   label: '设备RTSP地址',
  //   component: 'Input',
  //   colProps: { span: 6 },
  // },
];

export const formSchema: FormSchema[] = [
  {
    field: 'equipment_number',
    label: '设备编号',
    component: 'Input',
    show: false,
  },
  {
    field: 'name',
    label: '设备名称',
    component: 'Input',
    required: true,
  },
  {
    field: 'model',
    label: '型号',
    component: 'Input',
    required: true,
  },
  //  {
  //    field: 'group',
  //    label: '组别',
  //    component: 'Input',
  //    required: true,
  //  },

  {
    field: 'range',
    label: '监控范围',
    component: 'Input',
    required: true,
  },
  //  {
  //    label: '形态特征',
  //    field: 'description',
  //    component: 'InputTextArea',
  //  },
  //  {
  //   label: '形态特征',
  //   field: 'description',
  //   component: 'InputTextArea',
  // },
  // {
  //   label: '栖息环境',
  //   field: 'habitat',
  //   component: 'InputTextArea',
  // },
  // {
  //   label: '生活习性',
  //   field: 'live',
  //   component: 'InputTextArea',
  // },
  // {
  //   label: '繁殖方式',
  //   field: 'reproduction',
  //   component: 'InputTextArea',
  // },
  // {
  //   label: '图像',
  //   field: 'urls',
  //   required: false,
  //   component: 'Input',
  //   slot: 'urls',
  // },
];

export const hour = ref<SelectProps['options']>([
  { value: 0, label: '0' },
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
  { value: 5, label: '5' },
  { value: 6, label: '6' },
  { value: 7, label: '7' },
  { value: 8, label: '8' },
  { value: 9, label: '9' },
  { value: 10, label: '10' },
  { value: 11, label: '11' },
  { value: 12, label: '12' },
  { value: 13, label: '13' },
  { value: 14, label: '14' },
  { value: 15, label: '15' },
  { value: 16, label: '16' },
  { value: 17, label: '17' },
  { value: 18, label: '18' },
  { value: 19, label: '19' },
  { value: 20, label: '20' },
  { value: 21, label: '21' },
  { value: 22, label: '22' },
  { value: 23, label: '23' },
]);

export const min = ref<SelectProps['options']>([
  { value: 0, label: '0' },
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
  { value: 5, label: '5' },
  { value: 6, label: '6' },
  { value: 7, label: '7' },
  { value: 8, label: '8' },
  { value: 9, label: '9' },
  { value: 10, label: '10' },
  { value: 11, label: '11' },
  { value: 12, label: '12' },
  { value: 13, label: '13' },
  { value: 14, label: '14' },
  { value: 15, label: '15' },
  { value: 16, label: '16' },
  { value: 17, label: '17' },
  { value: 18, label: '18' },
  { value: 19, label: '19' },
  { value: 20, label: '20' },
  { value: 21, label: '21' },
  { value: 22, label: '22' },
  { value: 23, label: '23' },
  { value: 24, label: '24' },
  { value: 25, label: '25' },
  { value: 26, label: '26' },
  { value: 27, label: '27' },
  { value: 28, label: '28' },
  { value: 29, label: '29' },
  { value: 30, label: '30' },
  { value: 31, label: '31' },
  { value: 32, label: '32' },
  { value: 33, label: '33' },
  { value: 34, label: '34' },
  { value: 35, label: '35' },
  { value: 36, label: '36' },
  { value: 36, label: '36' },
  { value: 37, label: '37' },
  { value: 38, label: '38' },
  { value: 39, label: '39' },
  { value: 40, label: '40' },
  { value: 41, label: '41' },
  { value: 42, label: '42' },
  { value: 43, label: '43' },
  { value: 44, label: '44' },
  { value: 45, label: '45' },
  { value: 46, label: '46' },
  { value: 47, label: '47' },
  { value: 48, label: '48' },
  { value: 49, label: '49' },
  { value: 50, label: '50' },
  { value: 51, label: '51' },
  { value: 52, label: '52' },
  { value: 53, label: '53' },
  { value: 54, label: '54' },
  { value: 55, label: '55' },
  { value: 56, label: '56' },
  { value: 57, label: '57' },
  { value: 58, label: '58' },
  { value: 59, label: '59' },
]);

export const sec = ref<SelectProps['options']>([
  { value: 0, label: '0' },
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
  { value: 5, label: '5' },
  { value: 6, label: '6' },
  { value: 7, label: '7' },
  { value: 8, label: '8' },
  { value: 9, label: '9' },
  { value: 10, label: '10' },
  { value: 11, label: '11' },
  { value: 12, label: '12' },
  { value: 13, label: '13' },
  { value: 14, label: '14' },
  { value: 15, label: '15' },
  { value: 16, label: '16' },
  { value: 17, label: '17' },
  { value: 18, label: '18' },
  { value: 19, label: '19' },
  { value: 20, label: '20' },
  { value: 21, label: '21' },
  { value: 22, label: '22' },
  { value: 23, label: '23' },
  { value: 24, label: '24' },
  { value: 25, label: '25' },
  { value: 26, label: '26' },
  { value: 27, label: '27' },
  { value: 28, label: '28' },
  { value: 29, label: '29' },
  { value: 30, label: '30' },
  { value: 31, label: '31' },
  { value: 32, label: '32' },
  { value: 33, label: '33' },
  { value: 34, label: '34' },
  { value: 35, label: '35' },
  { value: 36, label: '36' },
  { value: 36, label: '36' },
  { value: 37, label: '37' },
  { value: 38, label: '38' },
  { value: 39, label: '39' },
  { value: 40, label: '40' },
  { value: 41, label: '41' },
  { value: 42, label: '42' },
  { value: 43, label: '43' },
  { value: 44, label: '44' },
  { value: 45, label: '45' },
  { value: 46, label: '46' },
  { value: 47, label: '47' },
  { value: 48, label: '48' },
  { value: 49, label: '49' },
  { value: 50, label: '50' },
  { value: 51, label: '51' },
  { value: 52, label: '52' },
  { value: 53, label: '53' },
  { value: 54, label: '54' },
  { value: 55, label: '55' },
  { value: 56, label: '56' },
  { value: 57, label: '57' },
  { value: 58, label: '58' },
  { value: 59, label: '59' },
]);
